### ISSUE TITLE
Definir a arquitetura do projeto

### ISSUE THREAD

**Issue by DaviPierre** [DaviPierre/MDS_Project#6]
## Descrição

Definir a arquitetura para o projeto levando em conta os requisitos, limitações técnicas e limitações não técnicas do projeto.

## Objetivo

Ao definir a arquitetura do software será possível ter uma visão do macro para poder guiar corretamente a implementação do micro.

## Tarefas

- [x] Estudar o que é arquitetura de software
- [x] Conhecer as principais arquiteturas de software
- [x] Reconhecer qual melhor se encaixa no contexto do projeto

## Critério de aceitação

- Os colaboradores do projeto entrarão em um consenso a respeito de qual arquitetura será utilizada.

## Informações adicionais

Livros que abordam arquitetura de software:
- Clean Architecture. Disponível em: https://www.goodreads.com/book/show/18043011-clean-architecture
- Building Evolutionary Architectures: Support Constant Change. Disponível em: https://www.goodreads.com/book/show/35755822-building-evolutionary-architectures

**Comment by Yvestxt** [comment]
Olá, desenvolvi um esquemático da possível arquitetura utilizada neste projeto:

![Arquitetura](https://user-images.githubusercontent.com/73966483/236732471-f7b9ba05-68ef-49dc-bb4f-0a6b1ccff154.jpg)


A linguagem de programação utilizada é Python, que ficará responsável pelo algoritmo. Os dados salvos são acessados pela biblioteca Pandas e posteriormente analisados para fabricação dos gráficos/tabelas. A interação do usuário com o sistema é feita através de uma página web, desenvolvida em Python utilizando a biblioteca Streamlit.
