### ISSUE TITLE
Rascunho do front-end

### ISSUE THREAD

**Issue by DaviPierre** [DaviPierre/MDS_Project#8]
## Objetivo
Realizar a confeccção do rascunho da interface que será usada no software a ser desenvolvido.

## Tarefas
- [x] Apresentar o desenho do rascunho à equipe.
- [ ] Implementar o desenho apresentado no Figma, corrigindo/aprimorando a ideia

## Notas Final
Com isso, a equipe terá noção do que deverá ser implementado no front-end, além de como esses elementos serão integrados.

**Comment by JoelSRangel** [comment]
Tendo em vista o que será necessário para a entrega da primeira release, será postergado a implementação do desenho ao figma.
